### ISSUE TITLE
Containerizing a Simple PHP App

### ISSUE THREAD

**Issue by andybondar** [Arina-Zap/devops-course-task6a-cicd#1]
## PHP Code

* Remove everything from the `app` folder
* Create `index.php` file containing (for example) the following:
```php
<h1>Hello World!</h1>
<br>
<h2><?php echo "PHP Version: " . phpversion(); ?></h2>
<h2><?php echo "Server IP: " . $_SERVER['SERVER_ADDR']; ?></h2>
```
* Save the file in the `app` folder

## Dockerfile
```Dockerfile
FROM alpine:3.14.3

RUN apk --no-cache add apache2 php8-apache2
RUN rm -f /var/www/localhost/htdocs/index.html
COPY app/index.php /var/www/localhost/htdocs/index.php

CMD ["httpd", "-DFOREGROUND"]
EXPOSE 80
```

Now, please modify your `GitHub Actions` in order to continuously test the Application's ability to be build (containerized), run and respond to HTTP requests.

Should you have any questions, please let me know.

**Comment by Arina-Zap** [comment]
Done! Thank you :)
